### ISSUE TITLE
compressed mobs crash game 

### ISSUE THREAD

**Issue by lizardshaman** [Haydenman2/TBOBSB#2]
this has happened quite a few times to the point where i had to go into the config and disable them. what happens is the mob spawner we have fills with mobs and when one of the compressed mobs dies it goes over the mob limit and crashes the game for whoever killed it. will find the crash log later cause i dont know where it is right now

**Comment by Haydenman2** [comment]
This is an issue I cannot fix, this is a problem of both the devs of Ex Compressum and Mojang, however if this is a serious issue then I may change the default config setting to false.
